    stages {
        stage('Compile') {
            steps {
                echo 'Compiling project...'
                // Changed sh to bat
                bat 'mvn clean compile -q'
            }
        }

        stage('Run Tests') {
            steps {
                echo "Running tests with tags: ${params.TAGS} on ${params.BROWSER}"
                // Changed sh to bat and fixed the line continuation (Windows uses ^ instead of \)
                bat """
                    mvn test ^
                      -Dbrowser=${params.BROWSER} ^
                      -Dheadless=${env.HEADLESS} ^
                      -Denv=${params.ENV} ^
                      -Dcucumber.filter.tags="${params.TAGS}"
                """
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        // ... rest of your stages
    }
